format = '''
[â”Œâ”€>](#ff0055) $directory $git_branch$git_commit$git_metrics $fill $cmake$golang$lua
[â”‚](#ff0055)
$character
'''

add_newline = true

[directory]
format = '[î‚¶](fg:#ff0055)[ó°¤](fg:#ff0055 bg:#ff0055)[ðŸ•‡](fg:#00ffc8 bg:#ff0055)[ó°¤](fg:#ff0055 bg:#ff0055)[$path](fg:#00ffc8 bg:#ff0055)[î‚´](#ff0055)'
truncation_length = 1
truncate_to_repo = false
read_only = '(read only)'

[character]
format = '[â””â”€>](#ff0055) '

[git_commit]
commit_hash_length = 7
tag_disabled = false
only_detached = false

[git_metrics]
disabled = false
format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '

[fill]
symbol = ' '

[cmake]
format = '[î™† ($version )](#526a90)'

[golang]
format = '[î˜§ ($version )](#86c6d4)'

[lua]
format = '[î˜  ($version )](#020278)'
